# Generated by Django 5.1.2 on 2024-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Vidéo'), ('audio', 'Audio'), ('other', 'Autre')], default='other', max_length=10),
        ),
    ]
